### ISSUE TITLE
Rebase to v1.10.18 versions of vdb geth

### ISSUE THREAD

**Issue by i-norden** [vulcanize/eth-statediff-fill-service#3]
Child of https://github.com/vulcanize/go-ethereum/issues/231

- [x] v3 release that uses the new v1.10.18-statediff-3.2.1 release of vdb geth (off of https://github.com/vulcanize/eth-statediff-fill-service/tree/release-v3.0.0)
- [x] v4 release that uses the new v1.10.18-statediff-4.0.1-alpha release of vdb geth (off of https://github.com/vulcanize/eth-statediff-fill-service/tree/release-v4.0.0-alpha)

During this upgrade we may also need to update the dependencies on ipld-eth-server to the versions resultant of https://github.com/vulcanize/ipld-eth-server/issues/158

**Comment by abdulrabbani00** [comment]
@ashwinphatak - I noticed that both master and the sharding branch are identical. Therefore, do we need a v3 release or only a v4 release (off of the main branch)?

**Comment by abdulrabbani00** [comment]
As per Ashwin's request, I will only cut the release for V4, V3 will be taken care of by his team.

Final:
V3 - https://github.com/vulcanize/eth-statediff-fill-service/releases/tag/v3.0.1
V4 - https://github.com/vulcanize/eth-statediff-fill-service/releases/tag/v4.0.1-alpha
